name: Nightly Tests

on: 
  schedule:
    - cron: "0 6 * * 2,6"  # cron is UTC, this translates to 10 PM PST Mon and Fri.
  # This lets us trigger the workflow from a browser.
  workflow_dispatch:

# Run the native libraries first so that the native, Hybrid and React MobileSync tests 
# don't run simultaniously (to prevents flappers).
jobs:
  android-nightly:
    strategy:
      fail-fast: false
      matrix:
        lib: [SalesforceAnalytics, SalesforceSDK, SmartStore, MobileSync]
    uses: ./.github/workflows/reusable-lib-workflow.yaml
    with:
      lib: ${{ matrix.lib }}
    secrets: inherit
  android-nightly-Hybrid:
    if: success() || failure()
    needs: [android-nightly]
    strategy:
      fail-fast: false
      matrix:
        lib: [SalesforceHybrid]
    uses: ./.github/workflows/reusable-lib-workflow.yaml
    with:
      lib: ${{ matrix.lib }}
    secrets: inherit
  android-nightly-React:
    if: success() || failure()
    needs: [android-nightly-Hybrid]
    strategy:
      fail-fast: false
      matrix:
        lib: [SalesforceReact]
    uses: ./.github/workflows/reusable-lib-workflow.yaml
    with:
      lib: ${{ matrix.lib }}
    secrets: inherit
  android-nightly-UI-Tests:
    uses: ./.github/workflows/reusable-ui-workflow.yaml
    secrets: inherit